{% set version = "2.10" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/archive/{{ version }}.tar.gz
  sha256: 7efa5951df06d4eab29add81544e31df0a5c7a11fb82c87c8e4bf0f13b0a99f5
    # or use https://hackage.haskell.org/package/pandoc-{{ version }}/pandoc-{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ghc 
    #binary_relocation: falsdie  # [osx]
    #missing_dso_whitelist:
    #- /usr/lib/libiconv.2.dylib  # [osx]
    #- /usr/lib/libz.1.dylib  # [osx]
    #- /usr/lib/libcharset.1.dylib  # [osx]
  host:
    # fix reqs
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - stack
    - ghc
    - python
  run:
    # fix reqs
    - python

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Universal markup converter

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
    - kiwi0fruit
