{% set version = "2.10.1" %}

package:
  name: pandoc
  version: {{ version }}  # [not ppc64le]

source:
  url:  https://hackage.haskell.org/package/pandoc-{{ version }}/pandoc-{{ version }}.tar.gz
  sha256: 938a4c9b0a7ed3de886c73af4052913b0ac9e4aa12b435bd2afd09670bd3229a

build:
  number: 0
  skip: true  # [win or osx or ppc64le]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ghc
    - cabal
    #binary_relocation: falsdie  # [osx]
    #missing_dso_whitelist:
    #- /usr/lib/libiconv.2.dylib  # [osx]
    #- /usr/lib/libz.1.dylib  # [osx]
    #- /usr/lib/libcharset.1.dylib  # [osx]
  host:
    # fix reqs
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ghc
    - cabal
    - python
  run:
    # fix reqs
    - python

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Universal markup converter
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/tree/master/doc

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
    - kiwi0fruit
    - step21
