{% set version = "2.1.3" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-amd64.deb    # [linux64]
  sha256: 9f700359cb5b17dd734902393678645c9152caec0871d0116b4c3c6556fd24c0

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.pkg      # [osx]
  sha256: 9f700359cb5b17dd734902393678645c9152caec0871d0116b4c3c6556fd24c0

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows.msi    # [win]
  sha256: 9f700359cb5b17dd734902393678645c9152caec0871d0116b4c3c6556fd24c0

build:
   number: 0

requirements:
  run:
    - gmp  # [linux64]
    - zlib 1.2.11  # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://pandoc.org/
  license: GPL-2.0
  summary: 'Universal markup converter (repackaged binaries).'

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
