{% set version = "3.12" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-amd64.tar.gz  # [linux and not aarch64]
  sha256: 67d7d011fed8c8543306022b985b9b2499ab9b74818df91d8727c7e9ebc5ba06  # [linux and not aarch64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-arm64.tar.gz  # [linux and aarch64]
  sha256: 6cefcf7100e23a99447c26f89d1ff5b253f3407fcef99a9e27ae06f3ed16cb82  # [linux and aarch64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-x86_64-macOS.zip  # [osx and not arm64]
  sha256: 18577f9460c3dc5d2651ad3bab37d513bc2034a5a777fbe18fa0a5acf2e936ea  # [osx and not arm64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-arm64-macOS.zip  # [osx and arm64]
  sha256: f148ca09c9f36594db527a9fc988ad736290ce428f79594c50208cd1ec58b3c0  # [osx and arm64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.zip  # [win]
  sha256: 2a77ebc2517d13e95056e76b1cd5b574cfe958ac61aa6058117d80c22ca19b79  # [win]

build:
  number: 0
  binary_relocation: false  # [osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]
    - /usr/lib/libz.1.dylib  # [osx]
    - /usr/lib/libcharset.1.dylib  # [osx]

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYRIGHT
  summary: The universal markup converter
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/blob/master/MANUAL.txt

extra:
  recipe-maintainers:
    - m-rossi
    - jankatins
    - ocefpaf
    - kiwi0fruit
