{% set version = "3.1.8" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/archive/refs/tags/{{ version }}.tar.gz  # [not aarch64]
  sha256: c0bfd5973e9b335372c7e1a594499f2acc2e30e1035cc2c21bd3dc76904385a5   # [not aarch64]
  # repackage for aarch64 until aarch64-build of stack is available, see https://github.com/conda-forge/stack-feedstock/pull/35
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 0d5770582781059a24fa24a21aa888657ecbee601545b3339081166055572ad7  # [aarch64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-arm64-macOS.zip  # [arm64]
  sha256: 064d5418d2d7ef56dbb8c9a69f8ff6313c1ac079d7dfafc49529c6d15842bcbe  # [arm64]

build:
  number: 0
  binary_relocation: false         # [osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib    # [osx]
    - /usr/lib/libz.1.dylib        # [osx]
    - /usr/lib/libcharset.1.dylib  # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}  # [linux and not aarch64]
    - pkg-config             # [osx and not arm64]
    - stack                  # [not aarch64 and not arm64]
  host:
    - zlib                   # [linux and not aarch64]
    - zlib                   # [osx and not arm64]
  run:
    - gmp                    # [linux and not aarch64]
    - zlib                   # [linux and not aarch64]

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYRIGHT
  summary: The universal markup converter
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/blob/master/MANUAL.txt

extra:
  recipe-maintainers:
    - m-rossi
    - jankatins
    - ocefpaf
    - kiwi0fruit
    - mfansler
