{% set version = "3.1.4" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/archive/refs/tags/{{ version }}.tar.gz  # [not aarch64 and not arm64]
  sha256: ff6a72b125e78b038e2e410028981301a000162f7e7693888b7c131e0f3ee6e8  # [not aarch64 and not arm64]
  # repackage for aarch64 until aarch64-build of stack is available, see https://github.com/conda-forge/stack-feedstock/pull/35
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: a9a10a085612879684186fd1031b0410e923fd45017c4494d8801ad3f84a9240  # [aarch64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-arm64-macOS.zip  # [arm64]
  sha256: 4d4d46815cae811812eb06b2779465b4b9e17532ddd75c912ee560f0be67fc10  # [arm64]

build:
  number: 0
  binary_relocation: false  # [osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]
    - /usr/lib/libz.1.dylib  # [osx]
    - /usr/lib/libcharset.1.dylib  # [osx]

requirements:
  build:
    - {{ compiler('c') }}  # [linux and not aarch64]
    - {{ compiler('cxx') }}  # [linux and not aarch64]
    - pkg-config  # [osx and not arm64]
    - stack  # [not aarch64 and not arm64]
  host:
    - zlib  # [linux and not aarch64]
    - zlib  # [osx and not arm64]
  run:
    - gmp  # [linux and not aarch64]
    - zlib  # [linux and not aarch64]

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYRIGHT
  summary: The universal markup converter
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/blob/master/MANUAL.txt

extra:
  recipe-maintainers:
    - m-rossi
    - jankatins
    - ocefpaf
    - kiwi0fruit
