{% set version = "3.8.3" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-amd64.tar.gz  # [linux and not aarch64]
  sha256: c224fab89f827d3623380ecb7c1078c163c769c849a14ac27e8d3bfbb914c9b4  # [linux and not aarch64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-arm64.tar.gz  # [linux and aarch64]
  sha256: 166a5a37387eb10bd4c4f242a8109beef755ac1e8d4eb039c6b5ebd1d918d8d7  # [linux and aarch64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-x86_64-macOS.zip  # [osx and not arm64]
  sha256: 922e35c0210d7ca20ee9327811361d6d7f0ef0adda089e0e74cb3756c3d713f9  # [osx and not arm64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-arm64-macOS.zip  # [osx and arm64]
  sha256: 3eaeb3bd10982aecba5dd76158745a4f805afb39ab72a519bba2533c98ce002d  # [osx and arm64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.zip  # [win]
  sha256: a77c14078a5c4c6e396d5f5c03f4849eff4a858414bb9e69560bb35528cbf57a  # [win]

build:
  number: 0
  binary_relocation: false  # [osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]
    - /usr/lib/libz.1.dylib  # [osx]
    - /usr/lib/libcharset.1.dylib  # [osx]

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYRIGHT
  summary: The universal markup converter
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/blob/master/MANUAL.txt

extra:
  recipe-maintainers:
    - m-rossi
    - jankatins
    - ocefpaf
    - kiwi0fruit
