{% set version = "2.17.0.1" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-amd64.tar.gz  # [linux64]
  sha256: 108cf440a9111de27212e1b6f8459a211c414e3173ddfc07b65703cb39a66f09  # [linux64]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.zip  # [osx]
  sha256: e72d2e22b15ee77a0727b35692a0f0582982874fb38dee5c25380af0c1b801c0  # [osx]

  fn: pandoc.msi  # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.msi  # [win]
  sha256: 16265e7d0f04b3f8864f447d7692544ce7b1efeb0aa13a5f89f5026683a428d2  # [win]

build:
  number: 0
  binary_relocation: false  # [osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]
    - /usr/lib/libz.1.dylib  # [osx]
    - /usr/lib/libcharset.1.dylib  # [osx]

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYRIGHT
  summary: The universal markup converter (repackaged binaries)
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - kiwi0fruit
    - ickc
