{% set version = "2.10.1" %}

package:
  name: pandoc
  version: {{ version }}  # [not ppc64le]
  version: 2.2.1  # [ppc64le]

source:
  url: https://github.com/jgm/pandoc/archive/{{ version }}.tar.gz
  sha256: 7efa5951df06d4eab29add81544e31df0a5c7a11fb82c87c8e4bf0f13b0a99f5
    # or use https://hackage.haskell.org/package/pandoc-{{ version }}/pandoc-{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - ghc 
    #binary_relocation: falsdie  # [osx]
    #missing_dso_whitelist:
    #- /usr/lib/libiconv.2.dylib  # [osx]
    #- /usr/lib/libz.1.dylib  # [osx]
    #- /usr/lib/libcharset.1.dylib  # [osx]
  host:
    # fix reqs
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - stack
    - ghc
    - python
  run:
    # fix reqs
    - python

# The pandoc binary from the RPM depends on libgmp, libz and libffi and system libraries.
# Add these as host requirements to pick up the correct run_exports
{% if ARCH == "ppc64le" %}
requirements:
  build:
    - patchelf
    - {{ compiler('c') }}
  host:
    - gmp 6.1.2
    - zlib 1.2.11
    - libffi 3.3
{% endif %}

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Universal markup converter (repackaged binaries)
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/tree/master/doc

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
    - kiwi0fruit
