{% set version = "2.2.1" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-amd64.deb    # [linux64]
  sha256: 2a8c536721047c0512ad44d54da2908a937d604e1c29fcb948be3cb0cbe8842c

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.pkg      # [osx]
  sha256: 2a8c536721047c0512ad44d54da2908a937d604e1c29fcb948be3cb0cbe8842c

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.msi  # [win]
  sha256: 2a8c536721047c0512ad44d54da2908a937d604e1c29fcb948be3cb0cbe8842c

build:
   number: 0

requirements:
  run:
    - gmp  # [linux64]
    - zlib 1.2.11  # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://pandoc.org/
  license: GPL-2.0
  summary: 'Universal markup converter (repackaged binaries).'

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
