{% set version = "3.1.6" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/archive/refs/tags/{{ version }}.tar.gz  # [not aarch64]
  sha256: 6ca797f358b0cc04a3b9208ff1975a861bfa7110eafa881aa8c023ac4040e208  # [not aarch64]
  # repackage for aarch64 until aarch64-build of stack is available, see https://github.com/conda-forge/stack-feedstock/pull/35
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-linux-arm64.tar.gz  # [aarch64]
  sha256: 8c57ceb8e948d264cdd1269f5141de966a1f93b1b5099e65cdb92a6fee31f161  # [aarch64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-arm64-macOS.zip  # [arm64]
  sha256: 4fa822887474cf3a12c215bf9de5295f084ce4e30fc1267c96c696eddd88a912  # [arm64]

build:
  number: 0
  binary_relocation: false  # [osx]
  missing_dso_whitelist:
    - /usr/lib/libiconv.2.dylib  # [osx]
    - /usr/lib/libz.1.dylib  # [osx]
    - /usr/lib/libcharset.1.dylib  # [osx]

requirements:
  build:
    - pkg-config  # [osx and not arm64]
    - stack  # [not aarch64 and not arm64]
  host:
    - zlib  # [linux and not aarch64]
    - zlib  # [osx and not arm64]
  run:
    - gmp  # [linux and not aarch64]
    - zlib  # [linux and not aarch64]

test:
  commands:
    - type pandoc  # [osx]
    - pandoc --version
    - pandoc --help

about:
  home: http://pandoc.org/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYRIGHT
  summary: The universal markup converter
  description: |
    Pandoc is a Haskell library for converting from one markup format to
    another, and a command-line tool that uses this library.
  doc_url: http://pandoc.org/MANUAL.html
  dev_url: https://github.com/jgm/pandoc
  doc_source_url: https://github.com/jgm/pandoc/blob/master/MANUAL.txt

extra:
  recipe-maintainers:
    - m-rossi
    - jankatins
    - ocefpaf
    - kiwi0fruit
